name = "ai-tools-web"
compatibility_date = "2024-01-01"

[env.production]
name = "ai-tools-web"
route = "aitoolbox.uk/*"

[env.preview]
name = "ai-tools-web-preview"

[build]
command = ""
publish = "." 